'use client';
import {useEffect,useState} from 'react';import {ProtectedRoute,getAccessToken} from '../../lib/auth';import {offices} from '../../lib/data';
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||'').replace(/\/$/,'');
async function api(path:string,o:RequestInit={}){const t=getAccessToken();const r=await fetch(API+path,{...o,headers:{'Content-Type':'application/json',...(t?{Authorization:`Bearer ${t}`}:{})}});if(!r.ok)throw Error(await r.text());return r.json()}
function whole(value:unknown){const number=Number(value);return Number.isFinite(number)?String(Math.round(number)):'—'}
function Admin(){const [tab,setTab]=useState('overview'),[office,setOffice]=useState(''),[s,setS]=useState<any>(),[bo,setBo]=useState<any[]>([]),[daily,setDaily]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[windows,setWindows]=useState<any[]>([]),[transfers,setTransfers]=useState<any[]>([]),[err,setErr]=useState('');const [nu,setNu]=useState({username:'',password:'',role:'Staff',office:'Registrar'});
async function load(){try{setErr('');const q=office?`?office=${encodeURIComponent(office)}`:'';const [a,b,c,d,e,f]=await Promise.all([api('/api/admin/reports/summary'+q),api('/api/admin/reports/by-office'),api('/api/admin/reports/daily'),api('/api/admin/users'),api('/api/admin/windows'),api('/api/admin/transfers?limit=100')]);setS(a);setBo(b);setDaily(c);setUsers(d);setWindows(e);setTransfers(f)}catch(e:any){setErr(e.message)}}useEffect(()=>{load()},[office]);
async function create(e:any){e.preventDefault();try{await api('/api/admin/users',{method:'POST',body:JSON.stringify(nu)});setNu({username:'',password:'',role:'Staff',office:'Registrar'});load()}catch(e:any){setErr(e.message)}}async function toggle(u:any){try{await api('/api/admin/users/'+encodeURIComponent(u.username)+'/status',{method:'PUT',body:JSON.stringify({isActive:!u.isActive})});load()}catch(e:any){setErr(e.message)}}async function win(w:any){try{await api(`/api/admin/windows/${w.windowNumber}/status`,{method:'PUT',body:JSON.stringify({isActive:!w.isActive})});load()}catch(e:any){setErr(e.message)}}
return <div className="container"><div className="section-head"><div><div className="eyebrow">Administration</div><h2>CampusQ control center</h2><div className="muted">Performance, accounts, windows and audit history.</div></div><button className="btn btn-outline" onClick={load}>Refresh</button></div>{err&&<div className="error-box">{err}</div>}<div className="actions" style={{marginTop:0}}>{[['overview','Overview'],['users','Users'],['windows','Windows'],['transfers','Transfers']].map(x=><button className={`btn ${tab===x[0]?'btn-primary':'btn-outline'}`} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</div>
{tab==='overview'&&<><div className="section-head"><h2>Performance</h2><select className="input" style={{maxWidth:220}} value={office} onChange={e=>setOffice(e.target.value)}><option value="">All offices</option>{offices.map(o=><option key={o}>{o}</option>)}</select></div><div className="stat-grid">{[['Completed',s?whole(s.totalTickets):'—'],['Priority',s?whole(s.priorityTickets):'—'],['Avg wait',s?`${whole(s.avgWaitMinutes)} min`:'—'],['Wait range',s?`${whole(s.minWaitMinutes)}–${whole(s.maxWaitMinutes)} min`:'—']].map(x=><div className="card" key={x[0]}><div className="muted">{x[0]}</div><div className="big-stat">{x[1]}</div></div>)}</div><div className="grid cards"><div className="panel"><h3>By office</h3><table className="table"><thead><tr><th>Office</th><th>Tickets</th><th>Priority</th><th>Avg</th></tr></thead><tbody>{bo.map(x=><tr key={x.office}><td>{x.office}</td><td>{whole(x.tickets)}</td><td>{whole(x.priorityTickets)}</td><td>{whole(x.avgWaitMinutes)}m</td></tr>)}</tbody></table></div><div className="panel"><h3>Daily volume</h3><table className="table"><thead><tr><th>Date</th><th>Tickets</th><th>Avg</th></tr></thead><tbody>{daily.slice(0,10).map(x=><tr key={x.day}><td>{x.day}</td><td>{whole(x.tickets)}</td><td>{whole(x.avgWaitMinutes)}m</td></tr>)}</tbody></table></div></div></>}
{tab==='users'&&<div className="grid cards"><div className="panel"><h3>Create account</h3><form onSubmit={create}><input className="input" placeholder="Username" required value={nu.username} onChange={e=>setNu({...nu,username:e.target.value})}/><input className="input" style={{marginTop:10}} type="password" minLength={8} placeholder="Temporary password" required value={nu.password} onChange={e=>setNu({...nu,password:e.target.value})}/><select className="input" style={{marginTop:10}} value={nu.role} onChange={e=>setNu({...nu,role:e.target.value})}><option>Staff</option><option>Admin</option></select>{nu.role==='Staff'&&<select className="input" style={{marginTop:10}} value={nu.office} onChange={e=>setNu({...nu,office:e.target.value})}>{offices.map(o=><option key={o}>{o}</option>)}</select>}<button className="btn btn-primary" style={{marginTop:14}}>Create account</button></form></div><div className="panel"><h3>Accounts</h3><table className="table"><thead><tr><th>User</th><th>Role</th><th>Office</th><th>Status</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.username}><td>{u.username}</td><td>{u.role}</td><td>{u.office||'All'}</td><td>{u.isActive===false?'Inactive':'Active'}</td><td><button className="btn btn-outline" onClick={()=>toggle(u)}>{u.isActive===false?'Activate':'Deactivate'}</button></td></tr>)}</tbody></table></div></div>}
{tab==='windows'&&<div className="panel"><h3>Service windows</h3><div className="grid">{windows.map(w=><div className="card" key={w.windowNumber}><h3>Window {w.windowNumber}</h3><div className="muted">{w.isActive?'Active':'Disabled'}</div><button className="btn btn-outline" style={{marginTop:14}} onClick={()=>win(w)}>{w.isActive?'Disable':'Enable'}</button></div>)}</div></div>}
{tab==='transfers'&&<div className="panel"><h3>Transfer audit</h3><table className="table"><thead><tr><th>Ticket</th><th>From</th><th>To</th><th>Reason</th><th>Actor</th><th>Time</th></tr></thead><tbody>{transfers.map(x=><tr key={x.transferId}><td>#{x.ticketNumber}</td><td>{x.sourceOffice}</td><td>{x.targetOffice}</td><td>{x.reason}</td><td>{x.actor}</td><td>{new Date(x.transferredAt).toLocaleString()}</td></tr>)}</tbody></table></div>}</div>}
export default function ProtectedAdmin(){return <ProtectedRoute roles={['Admin']}><Admin/></ProtectedRoute>}
